-- ROUTE-P1-N2（扩展至 Oracle）：route_monitor_record 建表。
-- 由 ApiMonitoringRepository 原内嵌 DDL 按 Oracle 语义对齐外置而来，落库字段与三方言版本保持一致。
-- 保留 baselineOnMigrate 跳过执行语义；Oracle 不支持 CREATE TABLE IF NOT EXISTS，
-- 旧库迁移完全依赖 Flyway 基线（schema 非空即跳过），故不写 IF NOT EXISTS。

CREATE TABLE route_monitor_record (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint     VARCHAR2(500) NOT NULL,
    request_url  VARCHAR2(2000),
    method       VARCHAR2(10) NOT NULL,
    status_code  NUMBER(10) NOT NULL,
    req_headers  CLOB,
    res_headers  CLOB,
    res_body     CLOB,
    body_length  NUMBER(10),
    captured_at  TIMESTAMP(3) NOT NULL,
    test_run_id  VARCHAR2(100),
    assertion_ok NUMBER(1),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_endpoint ON route_monitor_record(endpoint);
CREATE INDEX idx_captured ON route_monitor_record(captured_at);
CREATE INDEX idx_test_run ON route_monitor_record(test_run_id);
